apiVersion: "deploy.razee.io/v1alpha1"
kind: RemoteResource
metadata:
  name: myremoteresource
  namespace: razee
spec:
  requests:
    - options:
         url: https://github.com/pulimounicareddy1/Test/blob/master/testdeploy.yaml
